baseURL = "https://dai-dinamici.github.io/"
description = "The Community of Italian Dynamicists"
languageCode = "en-US"
theme = "mainroad"
title = "DinAmicI"
[Params]
description = "The Community of Italian Dynamicists"
mainSections = ["news", "dai-seminars", "events", "open-positions"]
mathjax = true
mathjaxConfig = "TeX-AMS_SVG"
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js"
opengraph = true
pager = true
readmore = true
schema = true
twitter_cards = true
[Params.logo]
image = "wp-content/DAI1.png"
subtitle = "Dynamics, Applications, Interactions"
[Params.sidebar]
home = "left"
list = "left"
single = "left"
widgets = ["recent", "ddg-search", "sidemenu", "newsletter", "social"]
[Params.style.vars]
highlightColor = "#E5622A"
[Params.widgets]
recent_num = 5
[Params.widgets.social]
twitter = "dinamici"
[[Params.widgets.social.custom]]
icon = "svg/facebook.svg"
title = "Facebook"
url = "https://www.facebook.com/groups/1709850812592546"
[[Params.widgets.social.custom]]
icon = "svg/youtube.svg"
title = "Youtube"
url = "https://www.youtube.com/channel/UCyNNg155G3iLS7l-qZjboyg"
[outputFormats.Calendar]
protocol = "https://"
[permalinks]
posts = "/:year/:month/:slug/"
